language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install --upgrade pip setuptools
    - pip install -r dev-requirements.txt
    - pip install -e .

script: python runtests.py

after_failure: cat test/*.log

